# Generated by Django 4.1.1 on 2022-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transporter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
    ]
